apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "MakeDocWebinar"
  description: "This integrates everything with everything"
  annotations:
    github.com/project-slug: BehaimITS/MakeDoc-container
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  lifecycle: development
  owner: "group:default/tibco-templates"
  providesApis: ['bwce-integration-flow-api']
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bwce-integration-flow-api-location
spec:
  targets:
    - ./catalog-api.yaml
