site_name: "bwce-integration-flow"
site_description: "This integrates everything with everything"

# docs_dir: ./

nav:
  - Introduction: intro.md
  - Project documentation: projects/projects.md
  - Projects:
    - tibco.bwce.sample.binding.rest.BookStore.application: projects/tibco.bwce.sample.binding.rest.BookStore.application/tibco.bwce.sample.binding.rest.BookStore.application.md
    - Module Properties: projects/tibco.bwce.sample.binding.rest.BookStore.application/common/substvar.md
    - META-INF/default.substvar: projects/tibco.bwce.sample.binding.rest.BookStore.application/META-INF/default.substvar.md
    - META-INF/docker.substvar: projects/tibco.bwce.sample.binding.rest.BookStore.application/META-INF/docker.substvar.md
    - META-INF/local.substvar: projects/tibco.bwce.sample.binding.rest.BookStore.application/META-INF/local.substvar.md
    - Application settings: projects/tibco.bwce.sample.binding.rest.BookStore.application/common/application.md
    - Application: projects/tibco.bwce.sample.binding.rest.BookStore.application/META-INF/TIBCO.application.md

plugins:
  - techdocs-core
